### ISSUE TITLE
Pew Pew Live Kazakh

### ISSUE THREAD

**Issue by Qudratillayev** [pewpewlive/ppl-i18n#356]
Hello, I translated the game into Kazakh.
[PewPewKazakh.txt](https://github.com/pewpewlive/ppl-i18n/files/14561889/PewPewKazakh.txt)

**Comment by SKPG-Tech** [comment]
Thanks a lot for translating! 
We will add your translation to the game, and it should be available soon in the next following update. Make sure to check this repository monthly or in 2-4 week intervals to check for new strings to translate, but don't sweat it too much, missing strings are not the end of the world! Again thank you for translating!

**Comment by SKPG-Tech** [comment]
@Qudratillayev Just a few more questions:
* What name and color do you want in the translator credits?
* Does it make sense to use the Latin script instead of the Cyrillic one for future reference?
* How do you say "Kazakh" in your language? (write it in Latin or Cyrillic depending on the 2nd question)

Thanks again for translating, next time you are going to translate new strings into your language, you will have to fork this repository, edit the https://github.com/pewpewlive/ppl-i18n/blob/master/translations/kaz.po file in your fork, and make a pull request like so https://github.com/pewpewlive/ppl-i18n/pull/355. If you have questions, feel free to join our Discord server, we will give you a translator role so we can chat in a dedicated channel for translators.

**Comment by SKPG-Tech** [comment]
@Qudratillayev Checking up, if you can reply soon we'll be able to take care of this quickly!

**Comment by Qudratillayev** [comment]
In Kazakh, Kazakh is "Қазақша".

**Comment by SKPG-Tech** [comment]
@Qudratillayev Thanks, what about regarding the other two questions I mentioned?

**Comment by Qudratillayev** [comment]
Ali2008uzb in blue, white and green colours. I prefer to use the Cyrillic alphabet.

**Comment by SKPG-Tech** [comment]
> Ali2008uzb in blue, white and green colours. I prefer to use the Cyrillic alphabet.

Which parts of the name do you want it to be in blue white and green colors? As far as the writing system goes, whatever is better and easier is completely fine. I'm closing this as completed. Thanks!
