### ISSUE TITLE
vietnamese translation

### ISSUE THREAD

**Issue by hpxdev** [pewpewlive/ppl-i18n#435]
lots of pewpewlive players are vietnamese (counted 5 on top 100 of era 2 leaderboard) so it would be a reasonable choice to add vietnamese translation to the game

also, im pretty sure vietnamese translation is completely not in the game.

**Comment by SKPG-Tech** [comment]
Hello!

Yes, we can add Vietnamese. If I recall correctly, we at one point already tried, but didn't finish it. A lot has changed since so we can't reuse anything.

There are some concerns about adding Vietnamese specifically. It is not a font file that we use, every character you see in-game is drawn using a list of points and lines connecting them. We define those points by hand. And from what I can see, Vietnamese is pretty complex.

So there are a few things that could clear it up a bit for me:
- Are the tones separate from the letters, or are they one letter? (ligatures)
- How important is the placement of the tones on letters that have diacritics?
- Would you be willing to translate the game into Vietnamese?

It would be great if you could join our Discord server so we can discuss this efficiently!

**Comment by hpxdev** [comment]
yes, i speak vietnamese and im willing to translate it.

the tones are spearate from the letter, the placement of the tones on letters with diacritics arent important, they can be placed kn top. however you can place them based on the tone and diacritics (cosmetic but unneccesry).
